description = "KDE graphical file manager"

[packages]
present = [
  "dolphin", #KDE File Manager
  "dolphin-plugins", # Extra Dolphin plugins
  "kdenetwork-filesharing" # Properties dialog plugin to share a directory with the local network
]

[dotfiles]
"~/.config/dolphinrc" = { source = "home/.config/dolphinrc", mode = "symlink" }
"~/.local/share/kxmlgui5/dolphin" = { source = "home/.local/share/kxmlgui5/dolphin", mode = "symlink-each" }
