description = "GPU process monitor for AMD, Intel and NVIDIA"
[packages]
present = [
  "nvtop", # GPUs process monitoring for AMD, Intel and NVIDIA
]

[dotfiles]
"~/.config/nvtop" = { source = "home/.config/nvtop", mode = "symlink-each" }
