description = "Remote desktop clients and self-hosted game streaming"

[packages]
present = [
  "remmina", # remote desktop client written in GTK+
  "freerdp", # Free implementation of the Remote Desktop Protocol (RDP)
  "aur/rustdesk-bin", # Yet another remote desktop software, written in Rust. Works out of the box, no configuration required.
]
