description = "RustDesk remote desktop client with configuration"
[packages]
present = [
  "rustdesk",
]

[dotfiles]
"~/.config/rustdesk" = { source = "home/.config/rustdesk", mode = "symlink-each" }

[hooks]
post = ["sudo systemctl disable --now rustdesk"]
