description = "Polyglot dev-environment runtime version manager with config"
[packages]
present = [
  "mise", # The front-end to your dev env
]

[dotfiles]
"~/.config/mise" = { source = "home/.config/mise", mode = "symlink-each" }
