description = "KDE screen capture utility for screenshots and screen recordings"
[packages]
present = [
  "spectacle",
]

[dotfiles]
"~/.config/spectaclerc" = { source = "home/.config/spectaclerc", mode = "symlink" }
