description = "XSETTINGS daemon that propagates X11 application settings"
[packages]
present = [
  "xsettingsd",
]

[dotfiles]
"~/.config/xsettingsd" = { source = "home/.config/xsettingsd", mode = "symlink-each" }
