description = "XSETTINGS daemon that propagates X11 application settings"
[packages]
present = [
  "xsettingsd",
]

[dotfiles]
"~/.config/xsettingsd/xsettingsd.conf" = { source = "home/.config/xsettingsd/xsettingsd.conf", mode = "copy" }
