description = "DankMaterialShell desktop shell built on Quickshell with search, monitoring, and KDE Connect integration"

[packages]
present = [
  "dms-shell", # A Quickshell-based desktop shell with Material 3 design principles
  "aur/dankcalendar-bin", # Local, Google, Microsoft, and CalDAV calendars for the dank desktop (prebuilt binary)
  "quickshell", # The core framework for DMS (required)
  "dgop", # Stateless system and process monitoring tool with TUI, CLI, and REST API
  "aur/dsearch-bin", # Extremely fast indexed filesystem search service
  "accountsservice", # D-Bus interface for user account query and manipulation (for DMS user profiles)
  "i2c-tools", # Tools for accessing I2C devices (for DMS monitor backlight control)
  "kdeconnect", # Adds communication between KDE and your smartphone
]

[hooks]
post = [
    "dms plugins install dankKDEConnect || dms plugins update dankKDEConnect",
    "dms plugins install quickCapture || dms plugins update quickCapture",
    "dms plugins install dankCalendarAgenda || dms plugins update dankCalendarAgenda",
    "systemctl --user enable --now dcal"
]

[dotfiles]
"~/.config/DankMaterialShell" = { source = "home/.config/DankMaterialShell", mode = "symlink-each" }
