description = "Smart session manager for the terminal"
[packages]
present = [
  "aur/sesh-bin", # Smart session manager for the terminal
]

[dotfiles]
"~/.config/sesh" = { source = "home/.config/sesh", mode = "symlink-each" }
