description = "General-purpose terminal fuzzy finder with config"
[packages]
present = [
  "television", # A general purpose fuzzy finder for your terminal
]

[dotfiles]
"~/.config/television" = { source = "home/.config/television", mode = "symlink-each" }
