description = "GTK frontend for rsync to synchronize and back up folders"
[packages]
present = [
  "grsync", # GTK+ GUI for rsync to synchronize folders, files and make backups
]

[dotfiles]
"~/.config/grsync" = { source = "home/.config/grsync", mode = "symlink-each" }
