description = "System-wide Samba file sharing server configuration"
scope = "system"

[packages]
present = [
  "samba",
]

[dotfiles]
"/etc/samba/smb.conf" = { source = "home/etc/samba/smb.conf", mode = "copy" }
