description = "Panel Colorizer GNOME Shell extension and its configuration"

disabled = true

[packages]
present = [
  "aur/panel-colorizer",
]

[dotfiles]
"~/.config/panel-colorizer" = { source = "home/.config/panel-colorizer", mode = "symlink-each" }
