[linux1]
comment = linux1
path = /mnt/linux1
valid users = @smb
public = no
writable = yes

[linux2]
comment = linux2
path = /mnt/linux2
valid users = @smb
public = no
writable = yes

[linux3]
comment = linux3
path = /mnt/linux3
valid users = @smb
public = no
writable = yes

[linux4]
comment = linux4
path = /mnt/linux4
valid users = @smb
public = no
writable = yes

[ventoy]
comment = ventoy
path = /mnt/ventoy
valid users = @smb
public = no
writable = yes
