description = "Productivity apps for ebooks, office documents, command-line notes and text editing"
[packages]
present = [
  "calibre", # Ebook management application
  "aur/onlyoffice-bin", # An office suite that combines text, spreadsheet and presentation editors
  "jrnl", # Collect your thoughts and notes without leaving the command line
  "kate", # Advanced Text Editor
]
